#%RAML 1.0
title: update account
/updateaccount:
  get:
    queryParameters:
      name:
        example:
          sreeja
      id:
        example:
          '1001'
    responses:
                        200:
                                                              